### PR TITLE
(S3-inspired) Replace local temp file with remote stream

### PR DESCRIPTION
**Pull request by tvhung83**
### CHANGELOG
- Upgrade SDK to `com.google.cloud:google-cloud-storage:1.56.0`, bump to latest gradle wrapper & embulk
- Replace downloading `Object` to local temp files with `Blob`'s stream, just like S3
- Re-arrange some classes, for ex: `GcsAuthentication` → `RetryUtils` (as no need to init object)
- Add retry utility methods

### CODE REVIEW

**Review by sakama — APPROVED** [review]
Basically looks good to me.

I have bit concern about this changes.
Actually, we had read remote input stream directly before.
However this plugin sometimes got less record than actual records.
This is the reason we've used tmp file. https://github.com/embulk/embulk-input-gcs/pull/27 https://github.com/embulk/embulk-input-gcs/pull/33

If such problem will not happen, let's merge this PR.


P.S. Sorry, but my PR caused conflict https://github.com/embulk/embulk-input-gcs/pull/37

**Comment by tvhung83** [comment]
@sakama ah, that's good to know, let me do more end-to-end tests to see if I can reproduce previous issue, I will also add one more unit test before I can merge this. Will finish this in next week.

**Comment by tvhung83** [comment]
@sakama I've finished unit tests, please take a look later, thanks!

**Review by sakama — APPROVED** [review]
LGTM again.
Let's merge and test carefully. Thanks!

**Comment by tvhung83** [comment]
Thanks! Gonna merge now

**Pull request merged**
